version: '3.2'
services:
  mysql:
    container_name: 'adonis-ecommerce'
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_ROOT_PASSWORD: 'password'
